name: Upload Google Drive Folder

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests requests-toolbelt tqdm gdown

      - name: Upload files
        env:
          PW_TOKEN: ${{ secrets.PW_TOKEN }}
        run: |
          python upload_from_gdrive.py
