name: Upload Files

on:
  workflow_dispatch:


jobs:

  upload:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r uploader/requirements.txt

      - name: Create Firebase Credentials
        run: |
          cat > uploader/firebase.json << 'EOF'
          ${{ secrets.FIREBASE_JSON }}
          EOF

      ######################################################
      # CHANGE THESE VALUES WHEN NEEDED
      ######################################################

      - name: Run uploader
        working-directory: uploader

        env:

          PW_TOKEN: ${{ secrets.PW_TOKEN }}

          GDRIVE_API_KEY: ${{ secrets.GDRIVE_API_KEY }}

          #
          # Choose source
          #
          # drive
          # url
          #

          DOWNLOAD_SOURCE: url

          #
          # Single URL (optional)
          #

          DIRECT_URLS: |
           https://ct.animeheaven.me/video.mp4?11722945b16c4a8b9627e2d902e7a018&d
           https://cu.animeheaven.me/video.mp4?116aadc7db858aef15594b99a94e9505&d
           https://ct.animeheaven.me/video.mp4?4a7d3952fbf3aa20863628efec8ae491&d
           https://ax.animeheaven.me/video.mp4?3c721af98a7d8fe44e0560581f4d8c9c&d
           https://rk.animeheaven.me/video.mp4?dd4d7c92f4d9b5f0ef09ec6e1cc471d2&d

          #
          # Multiple URLs (optional)
          #

         # DIRECT_URLS: |
            # https://example.com/file1.mp4
            # https://example.com/file2.mkv

        run: |

          if [ "$DOWNLOAD_SOURCE" = "drive" ]; then

            echo "Using Google Drive source..."

            python upload_from_gdrive.py

          elif [ "$DOWNLOAD_SOURCE" = "url" ]; then

            echo "Using Direct URL source..."

            python upload_from_url.py

          else

            echo "Unknown DOWNLOAD_SOURCE: $DOWNLOAD_SOURCE"

            exit 1

          fi
